### ISSUE TITLE
When connecting to an FTDI device, claimInterface() is never called.

### ISSUE THREAD

**Issue by DaveMelcher** [ksksue/FTDriver#9]
Because of that, the system doesn't know to restrict access to that device.

If I use FTDriver to connect to an FTDI device, and later another app tries the same thing, the connection between the device and the first app is destroyed.  

This is an issue with multiple devices that require different apps, but all use the same FTDI chip.  

Why was the claimInterface() in setUSBInterface() commented out?

**Comment by ksksue** [comment]
It was TODO.
I had fixed.
Thanks.

**Comment by peplin** [comment]
Hi, I'm not sure I follow - the `claimInterface()` call is still commented out: https://github.com/ksksue/FTDriver/blob/master/FTDriver/src/jp/ksksue/driver/serial/FTDriver.java#L849

Like Dave says this causes problems when you have multiple devices attached, and I don't really see any reason why we shouldn't be claiming the USB interface. Is there a specific reason you don't want to claim it?

**Comment by ksksue** [comment]
Sorry It was not git push.

When I had been debugging, I had commented out.
The claimInterface often returns false because of often jumping the releaseInterface step.
I don't know why it can access without claimInterface, but I think it is a manner for exclusive.

When our app becomes non front activity, it should do releaseInterface for other apps claiming.
So we should write begin()(or claimInterface) on onResume and close()(or releaseInterface) on onPause.
